version: "3.8"

networks:
  internal:


services:
  server:
    build:
      context: src/api
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - api_db:/src/api/mashboard.db
      - api_db_shm:/src/api/mashboard.db-shm
      - api_db_wal:/src/api/mashboard.db-wal
    networks:
      - internal

  mail:
    build:
      context: src/mailserver
      dockerfile: Dockerfile
    ports:
      - "25:2525"
      - "8888:8888"

    volumes:
      - mail_db:/src/mailserver/mail.db
    networks:
      - internal

  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src/client/dist:/dist
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
      - mail
    restart: unless-stopped
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:
  api_db:
  api_db_shm:
  api_db_wal:
  mail_db:
