networks:
  internal:
  client-server:
    external: true

services:
  server:
    image: mashboard-server:local
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    secrets:
      - youtube_api_key
      - google_client_id
      - google_client_secret
      - jwt_secret
    volumes:
      - api_db:/data
    networks:
      - internal

  client:
    image: mashboard-client:local
    environment:
      - PORT=3030
      - PUBLIC_HOSTNAME=mashboard.app
      - PUBLIC_HOST_URL=https://mashboard.app
      - PUBLIC_PORT=3030
      - PUBLIC_API_BASE_URL=https://api.mashboard.app
    ports:
      - "3030:3030"
    networks:
      - client-server

  mail:
    image: mashboard-mail:local
    hostname: mashboard.app
    ports:
      - "25:25"
      - "8888:8888"

    volumes:
      - mail_db:/mail
    networks:
      - internal

  caddy:
    image: mashboard-caddy:local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src/client/build:/dist
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
      - mail
    networks:
      - internal
      - client-server
    deploy:
      restart_policy:
        condition: on-failure
secrets:
  youtube_api_key:
    external: true
  google_client_id:
    external: true
  google_client_secret:
    external: true
  jwt_secret:
    external: true

volumes:
  caddy_data:
  caddy_config:
  api_db:
  mail_db:


