networks:
  internal:
  client_server:
    external: true

services:
  server:
    build:
      context: src/api
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - api_db:/src/api/db
    networks:
      - internal

  client:
    build:
      context: src/client
      dockerfile: Dockerfile
    container_name: client_server
    environment:
      - PORT=3030
    ports:
      - "3030:3030"
    networks:
      - client_server

  mail:
    build:
      context: src/mailserver
      dockerfile: Dockerfile
    ports:
      - "25:2525"
      - "8888:8888"

    volumes:
      - mail_db:/src/mailserver/mail.db
    networks:
      - internal

  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src/client/build:/dist
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
      - mail
    restart: unless-stopped
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:
  api_db:
  mail_db:


